name: todo_reminder
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  cloud_firestore: ^6.0.0
  cupertino_icons: ^1.0.8
  firebase_core: ^4.0.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  # freezed系
  freezed_annotation: ^3.1.0
  intl: ^0.20.2
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.7.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.0
  json_serializable: ^6.10.0
  pedantic_mono: ^1.33.0
 
flutter:
  uses-material-design: true
