// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOwcBEQDL5EcnH1VJO08jKV8YghiFSaLU',
    appId: '1:754982974423:web:af82c89da34ed6b7415192',
    messagingSenderId: '754982974423',
    projectId: 'reminder-7bffc',
    authDomain: 'reminder-7bffc.firebaseapp.com',
    storageBucket: 'reminder-7bffc.firebasestorage.app',
    measurementId: 'G-1KQG5SCMDS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAotqgWRj77NWhfO6WE6lEMgGBebGJbAVc',
    appId: '1:754982974423:android:ff6a6ea63958c303415192',
    messagingSenderId: '754982974423',
    projectId: 'reminder-7bffc',
    storageBucket: 'reminder-7bffc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa0mlo86WIN_PdeS2EaJ7xPAclvOfhArw',
    appId: '1:754982974423:ios:7885ce9019afb9d1415192',
    messagingSenderId: '754982974423',
    projectId: 'reminder-7bffc',
    storageBucket: 'reminder-7bffc.firebasestorage.app',
    iosClientId: '754982974423-v8q6qe0jhpvuutof7acds90t4q2jnib2.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoReminder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa0mlo86WIN_PdeS2EaJ7xPAclvOfhArw',
    appId: '1:754982974423:ios:7885ce9019afb9d1415192',
    messagingSenderId: '754982974423',
    projectId: 'reminder-7bffc',
    storageBucket: 'reminder-7bffc.firebasestorage.app',
    iosClientId: '754982974423-v8q6qe0jhpvuutof7acds90t4q2jnib2.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoReminder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOwcBEQDL5EcnH1VJO08jKV8YghiFSaLU',
    appId: '1:754982974423:web:da66534688011f1f415192',
    messagingSenderId: '754982974423',
    projectId: 'reminder-7bffc',
    authDomain: 'reminder-7bffc.firebaseapp.com',
    storageBucket: 'reminder-7bffc.firebasestorage.app',
    measurementId: 'G-S9EB29SGGX',
  );
}
